### ISSUE TITLE
Make it Carthage compatible

### ISSUE THREAD

**Issue by sprint84** [gontovnik/DGRunkeeperSwitch#13]
Can you make it Carthage compatible?
It's not that hard, just add a Framework build scheme and make it shared.

**Comment by sprint84** [comment]
Thanks

**Comment by sprint84** [comment]
Actually can you make a new tag release with the version 1.1.2, that would make everything work?

**Comment by gontovnik** [comment]
https://github.com/gontovnik/DGRunkeeperSwitch/releases/tag/1.1.2
