### ISSUE TITLE
More than two options

### ISSUE THREAD

**Issue by caloon** [gontovnik/DGRunkeeperSwitch#19]
Really like what I see, but I would be interested in using DGRunkeeperSwitch with more than two options, more like a Segmented Control. Would be a great enhancement in my opinion!

Best,
Josef

**Comment by gontovnik** [comment]
Hi Josef, thank you for your interest in the component! I would appreciate if you would contribute with this feature :+1: 

Thanks,
Danil

**Comment by gontovnik** [comment]
My initial idea was just to copy Runkeeper's two tab switcher. But I am happy to have more features. :+1:

**Comment by efremidze** [comment]
:+1:

**Comment by inPhilly** [comment]
I think what saloon was saying wasn't to add more styling options, but to be able to have three or more segments. Great control, and I agree with caloon.

**Comment by HusamAamer** [comment]
Check out this one 👍 https://github.com/toashd/AnimatedSegmentSwitch

**Comment by gontovnik** [comment]
Implemented in #23
