### ISSUE TITLE
Two compiler Errors

### ISSUE THREAD

**Issue by irfanlone** [gontovnik/DGRunkeeperSwitch#2]
I am running this on lates xcode 7 beta 6.
1. changed this super.init(frame: CGRect.zeroRect) to super.init(frame: CGRect.zero)
2.The compiler was unable to solve the state at line 239 (rightTitleLabelFrame). i had to break this into two lines
        let tempPoint = CGPoint(x: floor(bounds.size.width / 2.0 + (bounds.width / 2.0 - rightTitleLabelSize.width) / 2.0), y: floor((bounds.height - rightTitleLabelSize.height) / 2.0))
        let rightTitleLabelFrame = CGRect(origin: tempPoint, size: rightTitleLabelSize)

**Comment by gontovnik** [comment]
I was building this project with Xcode 7 beta 4, maybe that is the issue. I will download Xcode 7 beta 6 today and will have a look. Thank you!
