### ISSUE TITLE
Swift 3 support

### ISSUE THREAD

**Issue by prettysunflower** [gontovnik/DGRunkeeperSwitch#33]

**Comment by nevinjethmalani** [comment]
Please let us know if you will be updating for 3.0. Thanks for your help. This is a great product.

**Comment by gokhanakkurt** [comment]
+1

**Comment by gokhanakkurt** [comment]
Forked and created `swift3` branch to support Swift 3.0. Check out from here [link](https://github.com/gokhanakkurt/DGRunkeeperSwitch/tree/swift3)

Add following snippet to your podfile and run `pod update` command.

`pod 'DGRunkeeperSwitch', :git => 'https://github.com/gokhanakkurt/DGRunkeeperSwitch.git', :branch => 'swift3'`

**Comment by gontovnik** [comment]
Just pushed to GitHub and CocoaPods Swift 3 support. Tag 1.1.4 :)
