### ISSUE TITLE
Fix Compilation issues with XCode 6.4 and update settings to make the sample app universal.

### ISSUE THREAD

**Issue by arjunkchr** [gontovnik/DGRunkeeperSwitch#4]
Couple of recommendations:
1. The project should have .gitignore file to ignore files generated during compilation.
2. With XCode 6.4, the compilation of the app fails.
        a. DGRunkeeperSwitch/UIKit.UIControl:25:18: Non-failable initializer 'init(coder:)' overridden here
        b. DGRunkeeperSwitch/DGRunkeeperSwitch/DGRunkeeperSwitch.swift:207:20: Cannot invoke 'animateWithDuration' with an argument list of type '(NSTimeInterval, delay: Double, usingSpringWithDamping: CGFloat, initialSpringVelocity: CGFloat, options: [UIViewAnimationOptions], animations: () -> Void, completion: (_) -> Void)'
        c. DGRunkeeperSwitch/DGRunkeeperSwitchExample/ViewController.swift:43:47: 'AnyObject.Protocol' does not have a member named 'FlexibleWidth'
3. Also, it might be more convenient to set the target as Universal for the sample app and let auto layout do its job, rather than having 1X and 2X indicators while running on iPad.

Cheers.

**Comment by gontovnik** [comment]
As you can see in requirements, it is built with Swift 2.0 and Xcode 7.0 beta. There will be no support for Xcode 6.4, because in a few weeks time Xcode 7.0 will be available for download. I will make it universal and will upload new version today later on.

**Comment by arjunkchr** [comment]
Thanks. I have asked a question in the SO community related to XCode 7 not being backward compatible with XCode 6.4. Also, Can we please also add .gitignore file to the repository, something like this:

.DS_Store

xcuserdata
*.xccheckout
*.xcuserstate

Thanks.
