### ISSUE TITLE
Can't create switch without titles

### ISSUE THREAD

**Issue by yakubbaev** [gontovnik/DGRunkeeperSwitch#44]
It fails with error `*** Terminating app due to uncaught exception ‘CALayerInvalidGeometry’, reason: ‘CALayer position contains NaN: [nan 15.5]’`
As a workaround - create with empty strings ("")

**Comment by gontovnik** [comment]
Hey, @yakubbaev. Why would you want to create it without any titles?

**Comment by yakubbaev** [comment]
I've already forgotten why I had to use that - and also I'm not working on that project anymore :)
